This project is very useful for a Data Analyst role because it combines:

Python
Pandas
EDA
AI Agent concepts

The agent will answer questions about a dataset automatically.

# Architecture
User

  ↓

Agent Brain

  ↓

Question Understanding

  ↓
  
+----------------------+

| Pandas Tools         |

+----------------------+

| Head Tool            |

| Describe Tool        |

| Missing Value Tool   |

| Average Tool         |

| Shape Tool           |

+----------------------+

# Import Libraries

In [1]:
import pandas as pd

# Load Dataset

In [2]:
df=pd.read_csv("employees.csv")
df.head()

    Name Department   Salary  Experience
0    Ram         IT  50000.0           2
1   Sita         HR  60000.0           5
2   John         IT  70000.0           4
3  David    Finance  80000.0           7
4   Sara         HR  55000.0           3

# Create Tools

Tool1 --> Show First Rows

In [3]:
def show_head():
    return df.head()

In [4]:
show_head()

    Name Department   Salary  Experience
0    Ram         IT  50000.0           2
1   Sita         HR  60000.0           5
2   John         IT  70000.0           4
3  David    Finance  80000.0           7
4   Sara         HR  55000.0           3

Tool2 --> Dataset Shape

In [5]:
def dataset_shape():
    rows,cols=df.shape

    return f"Rows: {rows}, Columns: {cols}"

In [6]:
dataset_shape()

'Rows: 7, Columns: 4'

Tool3-->Missing Values

In [7]:
def missing_values():
    return df.isnull().sum()

In [8]:
missing_values()

Name          0
Department    0
Salary        1
Experience    0
dtype: int64

Tool4 --> Summary Statistics

In [9]:
def summary_stats():
    return df.describe()

In [10]:
summary_stats()

             Salary  Experience
count      6.000000    7.000000
mean   67500.000000    4.428571
std    15411.035007    2.370453
min    50000.000000    2.000000
25%    56250.000000    2.500000
50%    65000.000000    4.000000
75%    77500.000000    6.000000
max    90000.000000    8.000000

Too15 --> Average Salary

In [11]:
def average_salary():
    return f"Average Salary: {df['Salary'].mean()}"

In [12]:
average_salary()

'Average Salary: 67500.0'

# Build the Agent Brain

In [13]:
def data_agent(question):
    question=question.lower()
    # Show head
    if "head" in question or "first rows" in question:
        return show_head()
    # Shape
    elif "shape" in question or "rows" in question or "columns" in question:
        return dataset_shape()
    #Missing Values
    elif "missing" in question or "null" in question:
        return missing_values()
    # Statistics
    elif "summary" in question or "statistics" in question:
        return summary_stats()
    # Average Salary
    elif "average salary" in question:
        return average_salary()
    
    else:
        return "I cannot understand your question."

# Run the Agent

In [ ]:
while True:
    user_question=input("Ask me about the dataset: ")
    if user_question.lower()=="exit":
        print("Goodbye!")
        break
    answer=data_agent(user_question)
    
    print(answer)

Rows: 7, Columns: 4
    Name Department   Salary  Experience
0    Ram         IT  50000.0           2
1   Sita         HR  60000.0           5
2   John         IT  70000.0           4
3  David    Finance  80000.0           7
4   Sara         HR  55000.0           3
I cannot understand your question.
Average Salary: 67500.0
Average Salary: 67500.0
             Salary  Experience
count      6.000000    7.000000
mean   67500.000000    4.428571
std    15411.035007    2.370453
min    50000.000000    2.000000
25%    56250.000000    2.500000
50%    65000.000000    4.000000
75%    77500.000000    6.000000
max    90000.000000    8.000000
Goodbye!

: